"""Initial Migration - Master Plan Compliant

Revision ID: ced523bbcc85
Revises: 
Create Date: 2026-03-11 21:00:29.590003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ced523bbcc85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('auth_provider_id', sa.String(), nullable=True),
    sa.Column('email_marketing_consent', sa.Boolean(), nullable=True),
    sa.Column('sms_marketing_consent', sa.Boolean(), nullable=True),
    sa.Column('default_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('total_spent', sa.Float(), nullable=True),
    sa.Column('average_order_value', sa.Float(), nullable=True),
    sa.Column('last_order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider_id')
    )
    op.create_index('idx_customers_total_spent', 'customers', [sa.literal_column('total_spent DESC')], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('compare_at_price', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('inventory_quantity', sa.Integer(), nullable=True),
    sa.Column('inventory_policy', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('seo_title', sa.String(), nullable=True),
    sa.Column('seo_description', sa.String(), nullable=True),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('wishlist_count', sa.Integer(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', title || ' ' || description)", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_search', 'products', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_handle'), 'products', ['handle'], unique=True)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('abandoned_carts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('recovered', sa.Boolean(), nullable=True),
    sa.Column('recovery_email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_email_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('abandoned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_abandoned_carts_recovered', 'abandoned_carts', ['recovered', 'abandoned_at'], unique=False)
    op.create_index(op.f('ix_abandoned_carts_customer_email'), 'abandoned_carts', ['customer_email'], unique=False)
    op.create_index(op.f('ix_abandoned_carts_recovered'), 'abandoned_carts', ['recovered'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('shipping', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('financial_status', sa.String(), nullable=True),
    sa.Column('fulfillment_status', sa.String(), nullable=True),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('tracking_url', sa.String(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_created', 'orders', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_orders_status', 'orders', ['financial_status', 'fulfillment_status'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('product_waitlist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_waitlist_compound', 'product_waitlist', ['product_id', 'customer_email'], unique=True)
    op.create_index(op.f('ix_product_waitlist_notified'), 'product_waitlist', ['notified'], unique=False)
    op.create_index(op.f('ix_product_waitlist_product_id'), 'product_waitlist', ['product_id'], unique=False)
    op.create_table('custom_quotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quote_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('doll_type', sa.String(), nullable=True),
    sa.Column('outfit_description', sa.String(), nullable=False),
    sa.Column('reference_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('special_requests', sa.String(), nullable=True),
    sa.Column('budget', sa.String(), nullable=True),
    sa.Column('deadline', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('quoted_price', sa.Float(), nullable=True),
    sa.Column('quoted_delivery_days', sa.Integer(), nullable=True),
    sa.Column('quote_valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('pdf_cloudinary_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('quoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('ai_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_quoted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quotes_created', 'custom_quotes', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_custom_quotes_customer_id'), 'custom_quotes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_custom_quotes_quote_number'), 'custom_quotes', ['quote_number'], unique=True)
    op.create_index(op.f('ix_custom_quotes_status'), 'custom_quotes', ['status'], unique=False)
    op.create_table('inventory_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_logs_product', 'inventory_logs', ['product_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_inventory_logs_product_id'), 'inventory_logs', ['product_id'], unique=False)
    op.create_table('product_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reviews_rating', 'product_reviews', ['product_id', sa.literal_column('rating DESC')], unique=False)
    op.create_index(op.f('ix_product_reviews_product_id'), 'product_reviews', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_reviews_status'), 'product_reviews', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_reviews_status'), table_name='product_reviews')
    op.drop_index(op.f('ix_product_reviews_product_id'), table_name='product_reviews')
    op.drop_index('idx_reviews_rating', table_name='product_reviews')
    op.drop_table('product_reviews')
    op.drop_index(op.f('ix_inventory_logs_product_id'), table_name='inventory_logs')
    op.drop_index('idx_inventory_logs_product', table_name='inventory_logs')
    op.drop_table('inventory_logs')
    op.drop_index(op.f('ix_custom_quotes_status'), table_name='custom_quotes')
    op.drop_index(op.f('ix_custom_quotes_quote_number'), table_name='custom_quotes')
    op.drop_index(op.f('ix_custom_quotes_customer_id'), table_name='custom_quotes')
    op.drop_index('idx_quotes_created', table_name='custom_quotes')
    op.drop_table('custom_quotes')
    op.drop_index(op.f('ix_product_waitlist_product_id'), table_name='product_waitlist')
    op.drop_index(op.f('ix_product_waitlist_notified'), table_name='product_waitlist')
    op.drop_index('idx_waitlist_compound', table_name='product_waitlist')
    op.drop_table('product_waitlist')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_abandoned_carts_recovered'), table_name='abandoned_carts')
    op.drop_index(op.f('ix_abandoned_carts_customer_email'), table_name='abandoned_carts')
    op.drop_index('idx_abandoned_carts_recovered', table_name='abandoned_carts')
    op.drop_table('abandoned_carts')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_handle'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index('idx_products_search', table_name='products', postgresql_using='gin')
    op.drop_table('products')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index('idx_customers_total_spent', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
